# Site wide configuration

title: Chris Meyns
description: "Philosopher"
logo: cm15-120.jpg
teaser: cm15-400.jpg
locale: en_US
url: http://0.0.0.0:4000/
# url: http://csmeyns.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Chris Meyns
  web: http://csmeyns.github.io
  email: c.s.meyns@gmail.com
  twitter: csmeyns
  bio: "Philosopher"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +c.s.meyns
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
